# Generated by Django 4.2.27 on 2026-05-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='証券コード')),
                ('name', models.CharField(max_length=120, verbose_name='企業名')),
                ('stock', models.CharField(blank=True, max_length=32, null=True, verbose_name='株価')),
                ('dividend', models.CharField(blank=True, max_length=32, null=True, verbose_name='配当金')),
                ('dividend_yield', models.CharField(blank=True, max_length=16, null=True, verbose_name='配当利回り')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='高配当ランキング')),
                ('date', models.DateField(blank=True, null=True, verbose_name='データ取得日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '企業',
                'verbose_name_plural': '企業一覧',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['code', 'date'], name='api_market__code_822950_idx')],
            },
        ),
    ]
