[Xeon001]
ipaddr = 192.168.64.2
hostname = rx8headnode
command = /home/accounts/cluster1_pacct.pl

[Xeon002]
ipaddr = 192.168.64.2
hostname = rx8headnode
command = /home/accounts/cluster2_pacct.pl

[Xeon003]
ipaddr = 192.168.64.2
hostname = rx8headnode
command = /home/accounts/cluster3_pacct.pl

; ヘッドノードが未確定/廃止予定のクラスタはコメントアウトで除外
;[cluster-l]
;ipaddr =
;hostname =