# Generated by Django 4.2.27 on 2026-05-19 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=10, verbose_name='証券コード')),
                ('company_name', models.CharField(max_length=128, verbose_name='企業名')),
                ('shares', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='保有株数')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='取得単価')),
                ('purchased_at', models.DateField(verbose_name='取得日')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ポートフォリオ',
                'verbose_name_plural': 'ポートフォリオ一覧',
                'ordering': ('company_code',),
                'unique_together': {('user', 'company_code', 'purchased_at')},
            },
        ),
    ]
